/*
 * This Java source file was generated by the Gradle 'init' task.
 *组件的创建工作，是容器完成的：
    Person对象的创建流程?
        
 *
 */

package com.ly;

import org.junit.Test;
import static org.junit.Assert.*;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.ly.Person;

public class AppTest {
    //从容器(ApplicationContext)中拿到这个组件(Person)
    @Test 
    public void test() {
        //ApplicationContext:代表ioc容器
        //ClassPathXmlApplicationContext:当前应用的xml配置文件在ClassPath下
        ApplicationContext ioc = new ClassPathXmlApplicationContext("ioc.xml");
        //容器帮我们创建好了对象
        System.out.println("容器启动完成。。");
        Person bean = (Person) ioc.getBean("person01");
        Object bean2 = ioc.getBean("person01");
        System.out.println(bean == bean2);//Person中的每个相同的person_id都是单实例
        
        //System.out.println("试图拿一个xml配置中不存在的person03..");
        //Object bean3 = ioc.getBean("person03");//编译会报错：org.springframework.beans.factory.NoSuchBeanDefinitionException
    }


}

